name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.PAT }}

      - name: Set up Git
        run: |
          git config --global user.email "oscar@gearedapp.co.uk"
          git config --global user.name "Oscar Meanwell"

      - name: Add the upstream repository
        run: git remote add upstream https://github.com/outline/outline.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into fork/main
        run: git merge upstream/main

      - name: Push changes to origin
        run: git push origin main
