name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge upstream
        run: |
          git config --global user.name 'Oscar Meanwell'
          git config --global user.email 'oscar@gearedapp.co.uk'
          git checkout main
          git pull --unshallow  
          git remote add upstream https://github.com/outline/outline.git
          git fetch upstream
          git checkout -b feature/x origin/feature/x
          git merge --no-edit upstream/feature/x
          git push origin feature/x

          git checkout main
          git merge --no-edit upstream/main
          git push origin main
